spring:
  application:
    name: gitem
  data:
    redis:
      timeout: 500ms
      connect-timeout: 500ms
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 5s

github:
  api:
    base-url: https://api.github.com